name: Screenshot Action

on:
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pwd
          dir
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Run python script
        run: |
          pwd
          dir
          python main.py

      - name: Commit and push screenshots
        run: |
          pwd
          dir
          git config --global user.email ${{ secrets.GH_EMAIL }}
          git config --global user.name ${{ secrets.GH_NAME }}
          git add img/
          git commit -m "Upload screenshots"
          git push
