name: Screenshot Action

on:
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python main.py

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Commit and push screenshots
        run: |
          pwd
#          git config --global user.email ${{ secrets.GH_EMAIL }}
#          git config --global user.name ${{ secrets.GH_NAME }}
#          git add img/
#          git commit -m "Add screenshots"
#          git push
